### ISSUE TITLE
Search form and comment form possible conflict (when on detail page)

### ISSUE THREAD

**Issue by danfolt** [andrzuk/FineCMS#1]
Andrzej I am not sure, but I think that there's a conflict between search form and comment form, when clicking on submit button when searching on category page search form works perfectly, when on detail post page with comment form it doesn't search, because of validation of comments text-area input, I wanted to control it also on your website (andrzej-zukowski.pl) because my website is already a little bit different, but You don't have categories with pages anymore, when You have a time pls.check it out on http://mvc.net.pl , You must be logged in and on detail page with comment form visible. I controlled Search form button (button class="btn-medium btn-primary full-width" type="submit" name="button-search ) and the comments form are totally different, comments form is here (button id="submit" class="btn btn-primary" type="submit" name="submit" value="Submit" )

**Comment by danfolt** [comment]
Sorry Andrzej, my fault I have forgot "</form>" at the end of the search form

**Comment by andrzuk** [comment]
It's OK, Daniel.
