### ISSUE TITLE
I have find a Reflected XSS vulnerability in this project

### ISSUE THREAD

**Issue by jgj212** [andrzuk/FineCMS#2]
Hello:
I have find a Reflected XSS vulnerability in this project.

The vulnerability exists due to insufficient filtration of user-supplied data in "action" HTTP parameter that will be passed to "FineCMS-master\index.php". The infected source code is line 46, there is no protection on $_GET['action']; if $_GET['action'] contains evil js code, line 48 will trigger untrusted code to be executed on the browser side.
![code1](https://cloud.githubusercontent.com/assets/1484292/23579768/927b293c-012f-11e7-8229-adbd3ff3104f.png)
![code2](https://cloud.githubusercontent.com/assets/1484292/23579782/b6791ccc-012f-11e7-9767-7b29c8671325.png)
![code3](https://cloud.githubusercontent.com/assets/1484292/23579892/1ced7294-0132-11e7-84fc-af36ce01220e.png)

So if a attacker construct a special url as follow and send it to a victim, when the victim click the url, the code which is contained in the url will be executed on the victim's browser side to do some evil.
http://your-web-root/FineCMS-master/index.php?action="><script>alert(1);</script><"

The follow scrrenshot is the result to click the upper url ( win7 spq x64 + firefox 51.0.1 32bit ):
![sc](https://cloud.githubusercontent.com/assets/1484292/23579902/41bf269e-0132-11e7-8e2d-f3f5f6f12830.png)

Discoverer: ADLab of Venustech

**Comment by danfolt** [comment]
Hi jgj212, I am not author of the script, but I also use this very nice script, do You also have suggestions to the author how to protect that part of the code?

**Comment by jgj212** [comment]
Oh, my god. i make a mistake in the issue. The infected module is "FineCMS-master\index.php", which will pass the http parameter to application.php with no security checking.  Do you mean that the application.php is not developmented by you? @danfolt

**Comment by danfolt** [comment]
You didn' make a mistake, https://github.com/andrzuk (author) can see it from your screenshots that the issue is in index.php passing parameters to application.php, I tried that malicious url and you are right, and yes I have not developed anything here on that script.

**Comment by jgj212** [comment]
Oh, you are a user of FineCMS? I am sorry, i thought you are the author of this CMS just now. The protection is just to checking parameter before pass to application.php. @danfolt

**Comment by danfolt** [comment]
Yes, I am only a user of this script, (still not as good as to be a real developer), but as I've seen your detailed description of the issue I had a feeling that You also already have a solution.

**Comment by andrzuk** [comment]
**jgj212**, thank you for pointing this vulnerability. I have just fixed it by adding strip_tags() filtration.

**Comment by jgj212** [comment]
@andrzuk tks, i got it

**Comment by danfolt** [comment]
@andrzuk I have made the changes in all four files and when I insert jgj212 javascript code into URL, I still see that alert, is it ok to see it? When I insert that in any other website it redirects me to 404 page not found

**Comment by andrzuk** [comment]
Daniel, download again whole project and copy updated files to your hosting. I tested it and this link should generate such message:

![js_test](https://cloud.githubusercontent.com/assets/736561/23620233/6e44805a-0296-11e7-994a-77161bde1a71.png)

instead of running java script code.
