### ISSUE TITLE
It is not an issue but an update (if author show only his posts/pages) for model/pages.php, sites.php, admin.php, images.php

### ISSUE THREAD

**Issue by danfolt** [andrzuk/FineCMS#3]
If **ADMIN** show all posts, if **OPERATOR** show all posts, if **USER** and _author_ show only his posts/pages + updated admin.php to show only his post's count, 
Andrzej if you want update also your script with following codes in screenshots you see below:

![screenshot 2017-03-14 19 59 57](https://cloud.githubusercontent.com/assets/777462/23918000/9e4ff200-08f1-11e7-8ba7-263047f01a1b.png)
![screenshot 2017-03-14 20 00 30](https://cloud.githubusercontent.com/assets/777462/23918002/9e56161c-08f1-11e7-8aba-8088b0fc9736.png)
![screenshot 2017-03-14 20 01 05](https://cloud.githubusercontent.com/assets/777462/23918001/9e50df1c-08f1-11e7-85c1-c5a77a9c53f9.png)

**Comment by danfolt** [comment]
I will also add images.php

**Comment by danfolt** [comment]
model/images.php  and model/admin.php(count) 

![admin php](https://cloud.githubusercontent.com/assets/777462/23927539/aa8f208a-091a-11e7-8038-e73fa5ed64f1.jpg)
![images php](https://cloud.githubusercontent.com/assets/777462/23927540/aa9168f4-091a-11e7-924f-faa81d949b6b.jpg)

**Comment by danfolt** [comment]
Also users should be fixed, users can see only 1 user(his profile) but Admin count shows 14(in my case)

![admin-users](https://cloud.githubusercontent.com/assets/777462/23928003/869d1aee-091d-11e7-8c7d-b91e0b87f329.jpg)

**Comment by danfolt** [comment]
Almost forgot comments, users see only his own comments count

![admin-comments](https://cloud.githubusercontent.com/assets/777462/23928187/a96f732c-091e-11e7-9409-619406504620.jpg)

**Comment by andrzuk** [comment]
Yes, Daniel, you are absolutely right! Thanks for your suggestion! I just commited these changes.

**Comment by danfolt** [comment]
Perfect, I will also use switch($table) case, case, it's much more better, thank you
