### ISSUE TITLE
Is it correct that stat/get_stat_data.php is using mysqli ?

### ISSUE THREAD

**Issue by danfolt** [andrzuk/FineCMS#5]
Is it correct that stat/get_stat_data.php is using MySQLi instead of PDO? I can't get chart data for last 2 month, but it is for sure my fault when find and replacing I probably overwrite some data, mysqli I have found when searching for that error.

**Comment by andrzuk** [comment]
Service get_stat_data.php is independent component, so you can use any db connection type you want. I used mysqli_connect and it works.

**Comment by danfolt** [comment]
Ahh ok, I didn't know that. Yes i have noticed that your websites works. I have somewhere a mistype. I only wanted to exclude this mysqli error.
