### ISSUE TITLE
Not issue, I have finished avatars in page/comments

### ISSUE THREAD

**Issue by danfolt** [andrzuk/FineCMS#6]
Not an issue Andrzej, but if You will ever want to add avatars to comments - or page articles or both, I have it fully working, because we already have a different scripts and design I will only publish here page.php (not even sure if the mode it was done is correct) but it works. It pulls user_image from user.php's user_image field.
![screenshot-inight club-2017-03-28-17-41-46](https://cloud.githubusercontent.com/assets/777462/24414168/e153193c-13dd-11e7-94e9-dbfaa954eaa0.png)
![screenshot-inight club-2017-03-28-17-41-09](https://cloud.githubusercontent.com/assets/777462/24414169/e336124a-13dd-11e7-9d6c-5d5b547155b2.png)

**Comment by danfolt** [comment]
`<?php

class Page_View extends View
{
	public function __construct($page)
	{
		parent::__construct($page);
	}

	public function ShowPage($data)
	{
		
		$result = NULL;

		if (is_array($data))
		{

			$data['social_buttons'] = str_replace(array('{{_url_}}', '{{_title_}}'), array($_SERVER['REQUEST_SCHEME'].'://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'], $data['title']), $data['social_buttons']);

			$result .= '<div class="article-skip">';
			$result .= '<span class="skip-left">';
			if ($data['skip_bar']['prev'])
				$result .= '<a href="index.php?route=page&id='.$data['skip_bar']['prev']['id'].'">Â« '.$data['skip_bar']['prev']['caption'].'</a>';
			$result .= '</span>';
			$result .= '<span class="skip-right">';
			if ($data['skip_bar']['next'])
				$result .= '<a href="index.php?route=page&id='.$data['skip_bar']['next']['id'].'">'.$data['skip_bar']['next']['caption'].' Â»</a>';
			$result .= '</span>';
			$result .= '</div>';
			$result .= '<div class="avatar">'; 
			$result .= $data['user_image'];           
			$result .= '</div>';
			$result .= '<div class="article">';
			$result .= '<div class="article-title">';
			$result .= '<h3>';
			$result .=  '#';
			$result .=  $data['id'];
			$result .=  ' ' . $data['title'];
			$result .= '</h3>';
			$result .= '</div>';
			$result .= '<div class="article-timestamp">';
			$result .= '<img src="img/16x16/user.png" />' . '<a href="index.php?route=users&action=view&id='.$data['user_id'].'">' . $data['user_login']. '</a>';			
			$result .= '<img src="img/16x16/date.png" />' . $data['modified'];
			$result .= '<img src="img/16x16/web.png" />' . $data['previews']; 
			$result .= $data['social_buttons'];
			$result .= '<div class="article-actions">';
			$result .= '<a href="index.php?route=pages&action=edit&id='.$data['id'].'">'.'<img src="img/16x16/edit.png" />'.'</a>';
			$result .= '</div>';       
			$result .= '</div>';
			$result .= '<div class="article-images">';		
			$result .= '<div class="article-image-cat">';
			$result .= '<img src="img/placeholder.jpg" />'; 
			$result .= '</div>';
			$result .= '<div class="article-image-feature">';
			$result .= '<img src="img/placeholder.jpg" />'; 
			$result .= '</div>';
			$result .= '</div>';
			$result .= '<div class="article-descript">';
			$result .= $data['description'] = substr($data['description'],0,290).'...';
			$result .= '</div>';
			$result .= '<div class="article-content">';
			if (is_array($data['contents']))
			{
				$result .= '<ul>';
				foreach ($data['contents'] as $element)
				{
					foreach ($element as $key => $value)
					{
						if ($key == 'caption') $caption = $value;
						if ($key == 'link') $link = $value;
					}
					$result .= '<li>'.'<a href="'.$link.'">'.$caption.'</a>'.'</li>';
				}
				$result .= '</ul>';
			}
			else
			{
				$result .= $data['contents'];
			}
			$result .= '</div>';
			$result .= '</div>';

			// Comments Panel:
			if ($data['comments_panel_visible'])
			{
				if (count($data['comments']))
				{
					// Comments List:
					
					$result .= '<div class="article-comments-list">';
					$result .= '<h2>' . '<img src="img/48x48/01.png" />' . ' Comments' . '</h2>';
					$result .= '<br>';
					foreach ($data['comments'] as $comment)
					{
						$result .= '<div class="article-single-comment">';
						$result .= '<div class="avatar">'; 
						$result .= $comment['user_image'];           
						$result .= '</div>';
						$result .= '<div class="article-comments-header">';
						$result .= '<img src="img/16x16/user.png" />' . '<a href="index.php?route=users&action=view&id='.$comment['user_id'].'">' . $comment['user_login']. '</a>';
						$result .= '<img src="img/16x16/date.png" />' . $comment['send_date'];
						$result .= '<img src="img/16x16/web.png" />' . $comment['ip'];
						$result .= '</div>';
						$result .= '<div class="article-comments-content">';
						$result .= '<p>' . $comment['comment_content'] . '</p>';
						$result .= '</div>';
						$result .= '</div>';
					}
					$result .= '</div>';
				}
				if ($data['logged_in'])
				{
					// Comment Form:
					$result .= '<div class="article-comment">';
					$result .= $this->ShowCommentForm($data['id']);
					$result .= '</div>';
				}
				else
				{
					// Login required for sending comments:
					$result .= '<div class="article-comments-info">';
					$result .= 'In order to write a comment, You have to be logged in. <a href="index.php?route=login">Log in here.</a>';
					$result .= '</div>';
				}
			}
		}

		return $result;
	}

	private function ShowCommentForm($id)
	{
		include GENER_DIR . 'form.php';

		$form_object = new FormBuilder();

		$form_title = '';
		
		$form_image = '';

		$form_width = '100%';
		
		$form_object->init($form_title, $form_width, $form_image);

		$form_action = 'index.php?route=' . MODULE_NAME . '&action=comment&id=' . $id;

		$form_object->set_action($form_action);


		$form_inputs = array(
			array(
				'caption' => 'Write a comment', 
				'data' => array(
					'type' => 'textarea', 'id' => 'contents', 'name' => 'contents', 'rows' => 2, 'value' => NULL, 'required' => 'required',
					),
				),
			);

		$form_object->set_inputs($form_inputs);
		
		$form_hiddens = array();

		$form_object->set_hiddens($form_hiddens);

		$form_buttons = array(
			array(
				'type' => 'submit', 'id' => 'comment', 'form' => 'comment', 'name' => 'comment', 'value' => 'Submit',
				),
			);
		
		$form_object->set_buttons($form_buttons);

		$result = $form_object->build_form();

		return $result;
	}
}

?>
`

**Comment by andrzuk** [comment]
Great job! It looks very well.
