### ISSUE TITLE
Portfolio page (4 columns)

### ISSUE THREAD

**Issue by danfolt** [andrzuk/FineCMS#8]
If ever needed, I got portfolio page(view/category.php) working
to implement:
` 
public function ShowPage($data)
	{
		$result = NULL;
        $num = 0;
        if (is_array($data))
		{
			$result .= '<table width="100%" cellpadding="5" cellspacing="5" align="center" id="results">';
            $result .= '<tr>';
			foreach ($data as $k => $v)
			{
				foreach ($v as $key => $value)
				{
`
.............................................
` 
	$result .= '</div>';
						}
					}
				}
				$result .= '</td>';
                if(($num+1) % 4 == 0) {
                    $result .= "</tr><tr>";
                }
                $num++;
			}
			$result .= '</tr>';
			$result .= '</table>';

`
![screenshot-inight club-2017-03-31-17-47-49](https://cloud.githubusercontent.com/assets/777462/24558466/8537dda8-163b-11e7-96ef-e41a3bf1c513.png)

css files if you need Andrzej feel free to ask me.

**Comment by andrzuk** [comment]
It looks great! I wonder what would look better - "No Image" label or some default avatar...

**Comment by danfolt** [comment]
This is exactly what i am trying to resolve now, I want to create feature_photo for every post type, it is  simple, but a little complicated at the end, because if I will add a new field in insert/update page and if I will want to grab the photo from the gallery 
(I like your idea of this type of gallery a lot, because people can upload all photos they have independently in it's image module/section  and then they can insert them into various sections - user profiles fields, pages fields, club fields, in future event fields etc)
, but when for example in pages I will have more than 2 image fields, I don't know yet how to choose to do not insert that photo into main_contents, but into new feature_photo field, so I will probably need to add some radio buttons choosing right field in new window asking me action before inserting `<img src=....../>` or new tab "Insert new feature photo" with only this single feature_photo field + submit button only this field to DB remembering last URL:
and then some simple function: 
 if agent pages (agent featured_photo) else (agent default photo avatar), if guest pages (guest feature_photo) else (guest default photo avatar), if candidate pages (candidate feature_photo) else (candidate default photo avatar),
I will be trying to implement different default photos for every page section(type), if you have idea how would you resolve and I should use 2 image fields in pages.php pls.let me know.

**Comment by danfolt** [comment]
btw. When speaking about images I will probably create a new gallery field in new gallery div with width=100%, before/after main_contents and I will allow users to insert those photos only there, it will be more ordered (in columns and rows), photos will have the same size, it will get feel of real gallery, fitting better to div (for example 2-3 photos next each other in rows , I expect to be more clean, rather than images mixed with text all over contents which many times breaks text and users have no idea how to move them, how to make them fit better. in only gallery images div it will have it's place.
